name: Package and Release Discord Bot

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f bot/requirements.txt ]; then pip install -r bot/requirements.txt; fi

      - name: Package bot folder
        run: |
          zip -r discord-bot-${{ github.ref_name }}.zip bot

      - name: Determine if prerelease
        id: prerelease
        run: |
          if [[ "${{ github.ref_name }}" =~ ^v0\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: discord-bot-${{ github.ref_name }}.zip
          prerelease: ${{ steps.prerelease.outputs.is_prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}